### PR TITLE
Add support for refined Char (lowercase and uppercase)

### PR DESCRIPTION
**Pull request by sindoudou**
Creating a PR here for discussion. Having compilation issues with Scala checks and PrismTest in CharSpec.

### CODE REVIEW

**Comment by sindoudou** [comment]
I am getting the following errors:

Error:(26, 37) could not find implicit value for evidence parameter of type org.scalacheck.Arbitrary[eu.timepit.refined.api.Refined[Char,monocle.refined.LowerCaseChar]]
  checkAll("lower cases", PrismTests(toCase[LowerCaseChar](Chars.lowerCaseChar)))
                                    ^


Error:(26, 37) not enough arguments for method apply: (implicit evidence$1: org.scalacheck.Arbitrary[Char], implicit evidence$2: scalaz.Equal[Char], implicit evidence$3: org.scalacheck.Arbitrary[eu.timepit.refined.api.Refined[Char,monocle.refined.LowerCaseChar]], implicit evidence$4: scalaz.Equal[eu.timepit.refined.api.Refined[Char,monocle.refined.LowerCaseChar]], implicit arbAA: org.scalacheck.Arbitrary[eu.timepit.refined.api.Refined[Char,monocle.refined.LowerCaseChar] => eu.timepit.refined.api.Refined[Char,monocle.refined.LowerCaseChar]])monocle.law.discipline.PrismTests.RuleSet in object PrismTests.
Unspecified value parameters evidence$3, evidence$4, arbAA.
  checkAll("lower cases", PrismTests(toCase[LowerCaseChar](Chars.lowerCaseChar)))
                                    ^

**Comment by julien-truffaut** [comment]
you're missing an instance of type: `Arbitrary[Refined[Char,LowerCaseChar]]`which is required in order to be able to generate random value of type `LowerCaseChar`. In `monocle.refined.BitsSpec`, you can see how we defined instances for `ByteBits`, `CharBits` and so on

**Comment by julien-truffaut** [comment]
It will compile if you change the bottom of `CharSpec` to: 
```
  implicit val lowerCaseCoGen: Cogen[LowerCaseChar] =
    Cogen[Char].contramap[LowerCaseChar](_.get)

  implicit val eqA: Equal[LowerCaseChar] = Equal.equalA[LowerCaseChar]
  implicit val eqS: Equal[Char] = Equal.equalA[Char]

  checkAll("lower cases", PrismTests(lowerCase))
```

**Comment by sindoudou** [comment]
@julien-truffaut great, thanks!

**Pull request merged**
